version: "3"

includes:
  _cfg:
    taskfile: .task/config/vars.yml
    internal: true

  rust:
    taskfile: .task/languages/rust.yml
  python:
    taskfile: .task/languages/python.yml
  node:
    taskfile: .task/languages/node.yml
  wasm:
    taskfile: .task/languages/wasm.yml
  ruby:
    taskfile: .task/languages/ruby.yml
  go:
    taskfile: .task/languages/go.yml
  java:
    taskfile: .task/languages/java.yml
  csharp:
    taskfile: .task/languages/csharp.yml
  php:
    taskfile: .task/languages/php.yml
  elixir:
    taskfile: .task/languages/elixir.yml

  _build_wf:
    taskfile: .task/workflows/build.yml
    internal: true
  _test_wf:
    taskfile: .task/workflows/test.yml
    internal: true
  _lint_wf:
    taskfile: .task/workflows/lint.yml
    internal: true
  _e2e_wf:
    taskfile: .task/workflows/e2e.yml
    internal: true
  benchmark:
    taskfile: .task/workflows/benchmark.yml

  version:
    taskfile: .task/tools/version-sync.yml
  pdfium:
    taskfile: .task/tools/pdfium.yml
  docs:
    taskfile: .task/tools/docs.yml
  typescript:
    taskfile: .task/tools/typescript.yml
  _tools:
    taskfile: .task/tools/general.yml
    flatten: true

vars:
  RUST_LOG: info

tasks:
  setup:
    desc: "Install all dependencies and initialize project. Idempotent - safe to re-run anytime."
    cmds:
      - cmd: >-
          bash -c '
          echo "Setting up sdkman...";
          if [ ! -d "$HOME/.sdkman" ]; then
            echo "Installing sdkman...";
            curl -s "https://get.sdkman.io" | bash;
          else
            echo "sdkman is already installed";
          fi;
          echo "Loading sdkman and installing tools from .sdkmanrc...";
          source "$HOME/.sdkman/bin/sdkman-init.sh";
          sdk env install;
          '
        platforms: [linux, darwin]
      - cmd: echo "Setting up sdkman (skipped on Windows - use scoop or manual installation)..."
        platforms: [windows]
      - echo "Installing language tools..."
      - task: rust:install
      - task: python:install
      - task: node:install
      - task: ruby:install
      - task: java:install
      - task: go:install
      - task: elixir:install
      - task: csharp:install
      - task: php:install
      - echo "Setup complete - safe to re-run anytime"

  build:
    desc: Build core libraries and language bindings
    cmds:
      - task: rust:build
      - task: python:build
      - task: ruby:build
      - task: node:build
      - task: java:build
      - task: csharp:build
      - task: php:build
      - task: elixir:build

  test:
    desc: Run test suites for all languages
    cmds:
      - task: rust:test
      - task: python:test
      - task: ruby:test
      - task: node:test
      - task: java:test
      - task: go:test
      - task: csharp:test
      - task: php:test
      - task: elixir:test

  check:
    desc: Run all linting and formatting checks via prek
    cmds:
      - task: lint

  update:
    desc: Update all dependencies to latest versions
    cmds:
      - echo "Updating Rust dependencies..."
      - task: rust:update
      - echo "Updating Python dependencies..."
      - task: python:update
      - echo "Updating TypeScript dependencies..."
      - task: node:update
      - echo "Updating WASM dependencies..."
      - task: wasm:update
      - echo "Updating Ruby dependencies..."
      - task: ruby:update
      - echo "Updating Java dependencies..."
      - task: java:update
      - echo "Updating Go dependencies..."
      - task: go:update
      - echo "Updating C# dependencies..."
      - task: csharp:update
      - echo "Updating PHP dependencies..."
      - task: php:update
      - echo "Updating Elixir dependencies..."
      - task: elixir:update
      - echo "Updating prek dependencies..."
      - prek autoupdate
      - echo "All dependencies updated"

  clean:
    desc: Clean all build artifacts
    cmds:
      - task: rust:clean
      - task: python:clean
      - task: ruby:clean
      - task: node:clean
      - task: java:clean
      - task: go:clean
      - task: csharp:clean
      - task: php:clean
      - task: elixir:clean
      - task: wasm:clean

  build:all:
    desc: Build all bindings across all languages
    cmds:
      - task: _build_wf:all

  build:all:dev:
    desc: Build all bindings in debug mode
    cmds:
      - task: _build_wf:all:dev

  build:all:release:
    desc: Build all bindings in release mode (optimized)
    cmds:
      - task: _build_wf:all:release

  build:all:ci:
    desc: Build all bindings in CI mode
    cmds:
      - task: _build_wf:all:ci

  test:all:
    desc: Run all tests across all languages
    cmds:
      - task: _test_wf:all

  test:all:parallel:
    desc: Run all tests in parallel (using deps)
    cmds:
      - task: _test_wf:all:parallel

  test:all:ci:
    desc: Run all tests in CI mode (with extra diagnostics)
    cmds:
      - task: _test_wf:all:ci

  lint:
    desc: Run all linters and formatters via prek (pre-commit framework)
    cmds:
      - prek run --all-files

  e2e:generate:all:
    desc: Generate all E2E tests from fixtures across all supported languages
    cmds:
      - task: _e2e_wf:generate:all

  e2e:test:all:
    desc: Run all E2E tests across all supported languages
    cmds:
      - task: _e2e_wf:test:all

  e2e:lint:all:
    desc: Lint all generated E2E test code
    cmds:
      - task: _e2e_wf:lint:all
