name: 'Setup PaddleOCR Models'
description: 'Download and cache PaddleOCR ONNX models for testing'

inputs:
  cache-key-prefix:
    description: 'Prefix for cache key'
    required: false
    default: 'paddle-ocr-models'

runs:
  using: 'composite'
  steps:
    - name: Cache PaddleOCR models
      uses: actions/cache@v4
      id: cache-models
      with:
        path: ~/.cache/kreuzberg/paddle-ocr
        key: ${{ inputs.cache-key-prefix }}-v1
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-

    - name: Download models if not cached
      if: steps.cache-models.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "PaddleOCR models not in cache, downloading..."
        CACHE_DIR="$HOME/.cache/kreuzberg/paddle-ocr"
        mkdir -p "$CACHE_DIR/det" "$CACHE_DIR/cls" "$CACHE_DIR/rec"

        # Model URLs from model_manager.rs - using Hugging Face hosted ONNX models
        BASE_URL="https://huggingface.co/Kreuzberg/paddleocr-onnx-models/resolve/main"

        # Download detection model (en_PP-OCRv4_det_infer.onnx)
        echo "Downloading detection model..."
        curl -L --retry 3 --retry-delay 5 -o "$CACHE_DIR/det/model.onnx" \
          "$BASE_URL/en_PP-OCRv4_det_infer.onnx"

        # Download classification model (ch_ppocr_mobile_v2.0_cls_infer.onnx)
        echo "Downloading classification model..."
        curl -L --retry 3 --retry-delay 5 -o "$CACHE_DIR/cls/model.onnx" \
          "$BASE_URL/ch_ppocr_mobile_v2.0_cls_infer.onnx"

        # Download recognition model (en_PP-OCRv4_rec_infer.onnx)
        echo "Downloading recognition model..."
        curl -L --retry 3 --retry-delay 5 -o "$CACHE_DIR/rec/model.onnx" \
          "$BASE_URL/en_PP-OCRv4_rec_infer.onnx"

        echo "Model download complete"

    - name: Verify models exist
      shell: bash
      run: |
        CACHE_DIR="$HOME/.cache/kreuzberg/paddle-ocr"
        echo "Checking for PaddleOCR models in $CACHE_DIR..."

        MISSING=0
        for model_type in det cls rec; do
          if [ -f "$CACHE_DIR/$model_type/model.onnx" ]; then
            SIZE=$(stat -f%z "$CACHE_DIR/$model_type/model.onnx" 2>/dev/null || stat -c%s "$CACHE_DIR/$model_type/model.onnx" 2>/dev/null || echo "unknown")
            echo "✓ $model_type model exists ($SIZE bytes)"
          else
            echo "✗ $model_type model MISSING"
            MISSING=1
          fi
        done

        if [ $MISSING -eq 1 ]; then
          echo "ERROR: Some models are missing!"
          exit 1
        fi

        echo "All PaddleOCR models are present"

        # Export cache environment variables
        echo "PADDLE_OCR_MODEL_CACHE=$CACHE_DIR" >> $GITHUB_ENV
        echo "KREUZBERG_CACHE_DIR=$HOME/.cache/kreuzberg" >> $GITHUB_ENV
