name: 'Build Wheels'
description: 'Build Python wheels using cibuildwheel'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'

outputs:
  artifact-name:
    description: 'Name of the uploaded artifact'
    value: wheels-${{ runner.os }}

runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Setup Python environment
      uses: ./.github/actions/setup-python-env
      with:
        python-version: ${{ inputs.python-version }}
        cache-prefix: python-build-wheels

    - name: Prepare ONNX Runtime caches
      # cibuildwheel runs separate builds per architecture; preload static libraries so ort-sys can link without downloading
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        set -euo pipefail
        if [ "${RUNNER_OS}" = "Linux" ]; then
          archs="x86_64 aarch64"
          base="/tmp/onnxruntime/linux"
        elif [ "${RUNNER_OS}" = "macOS" ]; then
          archs="x86_64 arm64"
          base="/tmp/onnxruntime/macos"
        else
          exit 0
        fi

        mkdir -p "${base}"
        for arch in ${archs}; do
          case "${RUNNER_OS}:${arch}" in
            Linux:x86_64)
              ort_url="https://cdn.pyke.io/0/pyke:ort-rs/ms@1.22.0/x86_64-unknown-linux-gnu.tgz"
              ;;
            Linux:aarch64)
              ort_url="https://cdn.pyke.io/0/pyke:ort-rs/ms@1.22.0/aarch64-unknown-linux-gnu.tgz"
              ;;
            macOS:x86_64)
              ort_url="https://cdn.pyke.io/0/pyke:ort-rs/ms@1.22.0/x86_64-apple-darwin.tgz"
              ;;
            macOS:arm64)
              ort_url="https://cdn.pyke.io/0/pyke:ort-rs/ms@1.22.0/aarch64-apple-darwin.tgz"
              ;;
            *)
              echo "Skipping unsupported combination ${RUNNER_OS}:${arch}"
              continue
              ;;
          esac
          dest="${base}/${arch}"
          if [ ! -f "${dest}/onnxruntime/lib/libonnxruntime.a" ]; then
            mkdir -p "${dest}"
            curl -fsSL "${ort_url}" | tar -xz -C "${dest}"
          fi
        done

    - name: Install cibuildwheel
      shell: bash
      run: uv tool install cibuildwheel

    - name: Build wheels
      shell: bash
      run: uvx cibuildwheel packages/python --output-dir wheelhouse
      env:
        CIBW_BUILD: cp310-*

        CIBW_ARCHS_LINUX: x86_64 aarch64
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_ARCHS_WINDOWS: AMD64

        CIBW_BUILD_FRONTEND: "build"
        CIBW_BUILD_VERBOSITY: 1

        CIBW_BEFORE_ALL_LINUX: >
          yum install -y openssl-devel pkgconfig &&
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
          source ~/.cargo/env
        CIBW_BEFORE_ALL_MACOS: >
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
          source ~/.cargo/env &&
          rustup target add x86_64-apple-darwin aarch64-apple-darwin
        CIBW_BEFORE_ALL_WINDOWS: >
          curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
          refreshenv

        CIBW_BEFORE_BUILD_LINUX: |
          python -m pip install --upgrade pip maturin build
          ARCH="${CIBUILDWHEEL_ARCH:-x86_64}"
          ORT_DIR="/tmp/onnxruntime/linux/${ARCH}"
          export ORT_LIB_LOCATION="${ORT_DIR}/onnxruntime"
          export ORT_SKIP_DOWNLOAD=1
          export ORT_PREFER_DYNAMIC_LINK=0
        CIBW_BEFORE_BUILD_MACOS: |
          python -m pip install --upgrade pip maturin build
          ARCH="${CIBUILDWHEEL_ARCH:-$(uname -m)}"
          ORT_DIR="/tmp/onnxruntime/macos/${ARCH}"
          export ORT_LIB_LOCATION="${ORT_DIR}/onnxruntime"
          export ORT_SKIP_DOWNLOAD=1
          export ORT_PREFER_DYNAMIC_LINK=0
        CIBW_BEFORE_BUILD_WINDOWS: >
          python -m pip install --upgrade pip maturin build &&
          python scripts/prepare_wheel.py

        CIBW_ENVIRONMENT: MATURIN_BUILD_ARGS="--compatibility linux" ORT_LIB_LOCATION=/tmp/onnxruntime/linux/${CIBUILDWHEEL_ARCH}/onnxruntime ORT_SKIP_DOWNLOAD=1 ORT_PREFER_DYNAMIC_LINK=0
        CIBW_ENVIRONMENT_WINDOWS: MATURIN_BUILD_ARGS=""
        CIBW_ENVIRONMENT_MACOS: 'MATURIN_BUILD_ARGS="" MACOSX_DEPLOYMENT_TARGET=10.12 ORT_LIB_LOCATION=/tmp/onnxruntime/macos/${CIBUILDWHEEL_ARCH}/onnxruntime ORT_SKIP_DOWNLOAD=1 ORT_PREFER_DYNAMIC_LINK=0'

        CIBW_SKIP: "*-win32 *-manylinux_i686"

        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
        CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
        CIBW_MUSLLINUX_X86_64_IMAGE: musllinux_1_2
        CIBW_MUSLLINUX_AARCH64_IMAGE: musllinux_1_2

        CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""
        CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
        CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: ""

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ runner.os }}
        path: ./wheelhouse/*.whl
        retention-days: 7
