name: Smoke test Node.js package
description: Tests Node.js package installation and functionality

inputs:
  package-tarball:
    description: Path to the npm package tarball (.tgz file)
    required: false
    default: ""
  package-spec:
    description: Explicit Node package spec (file:... or tarball path). Overrides workspace/tarball resolution.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Smoke test Node.js package
      shell: bash
      env:
        KREUZBERG_NODE_PKG: ${{ github.workspace }}/crates/kreuzberg-node
      run: |
        "$GITHUB_WORKSPACE/scripts/smoke-node.sh" "${{ inputs.package-tarball }}" "${{ inputs.package-spec }}"
