// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Kreuzberg;
using Xunit;
using Kreuzberg.E2E;

namespace Kreuzberg.E2E.Contract {
    public class ContractTests
    {
        [SkippableFact]
        public async Task ApiBatchBytesAsync()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var fileBytes = await File.ReadAllBytesAsync(documentPath);
            var mimeType = KreuzbergClient.DetectMimeType(fileBytes);
            var results = await KreuzbergClient.BatchExtractBytesAsync(new[] { new BytesWithMime(fileBytes, mimeType) }, config);
            var result = results[0];
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertContentContainsAny(result, new[] { "May 5, 2023", "Mallori" });
        }

        [SkippableFact]
        public void ApiBatchBytesSync()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var fileBytes = File.ReadAllBytes(documentPath);
            var mimeType = KreuzbergClient.DetectMimeType(fileBytes);
            var results = KreuzbergClient.BatchExtractBytesSync(new[] { new BytesWithMime(fileBytes, mimeType) }, config);
            var result = results[0];
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertContentContainsAny(result, new[] { "May 5, 2023", "Mallori" });
        }

        [SkippableFact]
        public async Task ApiBatchFileAsync()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var results = await KreuzbergClient.BatchExtractFilesAsync(new[] { documentPath }, config);
            var result = results[0];
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertContentContainsAny(result, new[] { "May 5, 2023", "Mallori" });
        }

        [SkippableFact]
        public void ApiBatchFileSync()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var results = KreuzbergClient.BatchExtractFilesSync(new[] { documentPath }, config);
            var result = results[0];
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertContentContainsAny(result, new[] { "May 5, 2023", "Mallori" });
        }

        [SkippableFact]
        public async Task ApiExtractBytesAsync()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var fileBytes = await File.ReadAllBytesAsync(documentPath);
            var mimeType = KreuzbergClient.DetectMimeType(fileBytes);
            var result = await KreuzbergClient.ExtractBytesAsync(fileBytes, mimeType, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertContentContainsAny(result, new[] { "May 5, 2023", "Mallori" });
        }

        [SkippableFact]
        public void ApiExtractBytesSync()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var fileBytes = File.ReadAllBytes(documentPath);
            var mimeType = KreuzbergClient.DetectMimeType(fileBytes);
            var result = KreuzbergClient.ExtractBytesSync(fileBytes, mimeType, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertContentContainsAny(result, new[] { "May 5, 2023", "Mallori" });
        }

        [SkippableFact]
        public async Task ApiExtractFileAsync()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = await KreuzbergClient.ExtractFileAsync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertContentContainsAny(result, new[] { "May 5, 2023", "Mallori" });
        }

        [SkippableFact]
        public void ApiExtractFileSync()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertContentContainsAny(result, new[] { "May 5, 2023", "Mallori" });
        }

        [SkippableFact]
        public void ConfigChunking()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig("{\"chunking\":{\"max_chars\":500,\"max_overlap\":50}}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertChunks(result, 1, null, true, null);
        }

        [SkippableFact]
        public void ConfigForceOcr()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig("{\"force_ocr\":true}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 5);
        }

        [SkippableFact]
        public void ConfigImages()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/embedded_images_tables.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/embedded_images_tables.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/embedded_images_tables.pdf", true);
            var config = TestHelpers.BuildConfig("{\"images\":{\"extract_images\":true}}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertImages(result, 1, null, null);
        }

        [SkippableFact]
        public void ConfigLanguageDetection()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig("{\"language_detection\":{\"enabled\":true}}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertDetectedLanguages(result, new[] { "eng" }, 0.5);
        }

        [SkippableFact]
        public void ConfigPages()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/multi_page.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/multi_page.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/multi_page.pdf", true);
            var config = TestHelpers.BuildConfig("{\"pages\":{\"end\":3,\"start\":1}}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

        [SkippableFact]
        public void ConfigUseCacheFalse()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig("{\"use_cache\":false}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

        [SkippableFact]
        public void OutputFormatDjot()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig("{\"output_format\":\"djot\"}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

        [SkippableFact]
        public void OutputFormatHtml()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig("{\"output_format\":\"html\"}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

        [SkippableFact]
        public void OutputFormatMarkdown()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig("{\"output_format\":\"markdown\"}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

        [SkippableFact]
        public void OutputFormatPlain()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig("{\"output_format\":\"plain\"}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

        [SkippableFact]
        public void ResultFormatElementBased()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig("{\"result_format\":\"element_based\"}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertElements(result, 1, null);
        }

        [SkippableFact]
        public void ResultFormatUnified()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig("{\"result_format\":\"unified\"}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

    }
}
