// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Kreuzberg;
using Xunit;
using Kreuzberg.E2E;

namespace Kreuzberg.E2E.Email {
    public class EmailTests
    {
        [SkippableFact]
        public void EmailSampleEml()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("email/sample_email.eml");
            TestHelpers.SkipIfOfficeTestOnWindows("email/sample_email.eml");
            var documentPath = TestHelpers.EnsureDocument("email/sample_email.eml", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "message/rfc822" });
            TestHelpers.AssertMinContentLength(result, 20);
        }

    }
}
