// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Kreuzberg;
using Xunit;
using Kreuzberg.E2E;

namespace Kreuzberg.E2E.Html {
    public class HtmlTests
    {
        [SkippableFact]
        public void HtmlComplexLayout()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("web/taylor_swift.html");
            TestHelpers.SkipIfOfficeTestOnWindows("web/taylor_swift.html");
            var documentPath = TestHelpers.EnsureDocument("web/taylor_swift.html", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "text/html" });
            TestHelpers.AssertMinContentLength(result, 1000);
        }

        [SkippableFact]
        public void HtmlSimpleTable()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("web/simple_table.html");
            TestHelpers.SkipIfOfficeTestOnWindows("web/simple_table.html");
            var documentPath = TestHelpers.EnsureDocument("web/simple_table.html", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "text/html" });
            TestHelpers.AssertMinContentLength(result, 100);
            TestHelpers.AssertContentContainsAll(result, new[] { "Product", "Category", "Price", "Stock", "Laptop", "Electronics", "Sample Data Table" });
        }

    }
}
