// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Kreuzberg;
using Xunit;
using Kreuzberg.E2E;

namespace Kreuzberg.E2E.Image {
    public class ImageTests
    {
        [SkippableFact]
        public void ImageMetadataOnly()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("images/example.jpg");
            TestHelpers.SkipIfOfficeTestOnWindows("images/example.jpg");
            var documentPath = TestHelpers.EnsureDocument("images/example.jpg", true);
            var config = TestHelpers.BuildConfig("{\"ocr\":null}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "image/jpeg" });
            TestHelpers.AssertMaxContentLength(result, 100);
        }

    }
}
