// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Kreuzberg;
using Xunit;
using Kreuzberg.E2E;

namespace Kreuzberg.E2E.Office {
    public class OfficeTests
    {
        [SkippableFact]
        public void OfficeDocLegacy()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("legacy_office/unit_test_lists.doc");
            TestHelpers.SkipIfOfficeTestOnWindows("legacy_office/unit_test_lists.doc");
            var documentPath = TestHelpers.EnsureDocument("legacy_office/unit_test_lists.doc", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/msword" });
            TestHelpers.AssertMinContentLength(result, 20);
        }

        [SkippableFact]
        public void OfficeDocxBasic()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("office/document.docx");
            TestHelpers.SkipIfOfficeTestOnWindows("office/document.docx");
            var documentPath = TestHelpers.EnsureDocument("office/document.docx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

        [SkippableFact]
        public void OfficeDocxEquations()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("documents/equations.docx");
            TestHelpers.SkipIfOfficeTestOnWindows("documents/equations.docx");
            var documentPath = TestHelpers.EnsureDocument("documents/equations.docx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
            TestHelpers.AssertMinContentLength(result, 20);
        }

        [SkippableFact]
        public void OfficeDocxFake()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("documents/fake.docx");
            TestHelpers.SkipIfOfficeTestOnWindows("documents/fake.docx");
            var documentPath = TestHelpers.EnsureDocument("documents/fake.docx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
            TestHelpers.AssertMinContentLength(result, 20);
        }

        [SkippableFact]
        public void OfficeDocxFormatting()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("documents/unit_test_formatting.docx");
            TestHelpers.SkipIfOfficeTestOnWindows("documents/unit_test_formatting.docx");
            var documentPath = TestHelpers.EnsureDocument("documents/unit_test_formatting.docx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
            TestHelpers.AssertMinContentLength(result, 20);
        }

        [SkippableFact]
        public void OfficeDocxHeaders()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("documents/unit_test_headers.docx");
            TestHelpers.SkipIfOfficeTestOnWindows("documents/unit_test_headers.docx");
            var documentPath = TestHelpers.EnsureDocument("documents/unit_test_headers.docx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
            TestHelpers.AssertMinContentLength(result, 20);
        }

        [SkippableFact]
        public void OfficeDocxLists()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("documents/unit_test_lists.docx");
            TestHelpers.SkipIfOfficeTestOnWindows("documents/unit_test_lists.docx");
            var documentPath = TestHelpers.EnsureDocument("documents/unit_test_lists.docx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
            TestHelpers.AssertMinContentLength(result, 20);
        }

        [SkippableFact]
        public void OfficeDocxTables()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("documents/docx_tables.docx");
            TestHelpers.SkipIfOfficeTestOnWindows("documents/docx_tables.docx");
            var documentPath = TestHelpers.EnsureDocument("documents/docx_tables.docx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
            TestHelpers.AssertMinContentLength(result, 50);
            TestHelpers.AssertContentContainsAll(result, new[] { "Simple uniform table", "Nested Table", "merged cells", "Header Col" });
            TestHelpers.AssertTableCount(result, 1, null);
        }

        [SkippableFact]
        public void OfficePpsxSlideshow()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("presentations/sample.ppsx");
            TestHelpers.SkipIfOfficeTestOnWindows("presentations/sample.ppsx");
            var documentPath = TestHelpers.EnsureDocument("presentations/sample.ppsx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.presentationml.slideshow" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

        [SkippableFact]
        public void OfficePptLegacy()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("legacy_office/simple.ppt");
            TestHelpers.SkipIfOfficeTestOnWindows("legacy_office/simple.ppt");
            var documentPath = TestHelpers.EnsureDocument("legacy_office/simple.ppt", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.ms-powerpoint" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

        [SkippableFact]
        public void OfficePptxBasic()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("presentations/simple.pptx");
            TestHelpers.SkipIfOfficeTestOnWindows("presentations/simple.pptx");
            var documentPath = TestHelpers.EnsureDocument("presentations/simple.pptx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.presentationml.presentation" });
            TestHelpers.AssertMinContentLength(result, 50);
        }

        [SkippableFact]
        public void OfficePptxImages()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("presentations/powerpoint_with_image.pptx");
            TestHelpers.SkipIfOfficeTestOnWindows("presentations/powerpoint_with_image.pptx");
            var documentPath = TestHelpers.EnsureDocument("presentations/powerpoint_with_image.pptx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.presentationml.presentation" });
            TestHelpers.AssertMinContentLength(result, 20);
        }

        [SkippableFact]
        public void OfficePptxPitchDeck()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("presentations/pitch_deck_presentation.pptx");
            TestHelpers.SkipIfOfficeTestOnWindows("presentations/pitch_deck_presentation.pptx");
            var documentPath = TestHelpers.EnsureDocument("presentations/pitch_deck_presentation.pptx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.presentationml.presentation" });
            TestHelpers.AssertMinContentLength(result, 100);
        }

        [SkippableFact]
        public void OfficeXlsLegacy()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("spreadsheets/test_excel.xls");
            TestHelpers.SkipIfOfficeTestOnWindows("spreadsheets/test_excel.xls");
            var documentPath = TestHelpers.EnsureDocument("spreadsheets/test_excel.xls", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.ms-excel" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

        [SkippableFact]
        public void OfficeXlsxBasic()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("spreadsheets/stanley_cups.xlsx");
            TestHelpers.SkipIfOfficeTestOnWindows("spreadsheets/stanley_cups.xlsx");
            var documentPath = TestHelpers.EnsureDocument("spreadsheets/stanley_cups.xlsx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
            TestHelpers.AssertMinContentLength(result, 100);
            TestHelpers.AssertContentContainsAll(result, new[] { "Team", "Location", "Stanley Cups" });
            TestHelpers.AssertTableCount(result, 1, null);
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "sheet_count", @"{""gte"": 2}");
            TestHelpers.AssertMetadata(metadataNode, "sheet_names", @"{""contains"": [""Stanley Cups""]}");
        }

        [SkippableFact]
        public void OfficeXlsxMultiSheet()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("spreadsheets/excel_multi_sheet.xlsx");
            TestHelpers.SkipIfOfficeTestOnWindows("spreadsheets/excel_multi_sheet.xlsx");
            var documentPath = TestHelpers.EnsureDocument("spreadsheets/excel_multi_sheet.xlsx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
            TestHelpers.AssertMinContentLength(result, 20);
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "sheet_count", @"{""gte"": 2}");
        }

        [SkippableFact]
        public void OfficeXlsxOfficeExample()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("office/excel.xlsx");
            TestHelpers.SkipIfOfficeTestOnWindows("office/excel.xlsx");
            var documentPath = TestHelpers.EnsureDocument("office/excel.xlsx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

    }
}
