// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Kreuzberg;
using Xunit;
using Kreuzberg.E2E;

namespace Kreuzberg.E2E.Smoke {
    public class SmokeTests
    {
        [SkippableFact]
        public void SmokeDocxBasic()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("documents/fake.docx");
            TestHelpers.SkipIfOfficeTestOnWindows("documents/fake.docx");
            var documentPath = TestHelpers.EnsureDocument("documents/fake.docx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
            TestHelpers.AssertMinContentLength(result, 20);
            TestHelpers.AssertContentContainsAny(result, new[] { "Lorem", "ipsum", "document", "text" });
        }

        [SkippableFact]
        public void SmokeHtmlBasic()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("web/simple_table.html");
            TestHelpers.SkipIfOfficeTestOnWindows("web/simple_table.html");
            var documentPath = TestHelpers.EnsureDocument("web/simple_table.html", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "text/html" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertContentContainsAny(result, new[] { "#", "**", "simple", "HTML" });
        }

        [SkippableFact]
        public void SmokeImagePng()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("images/sample.png");
            TestHelpers.SkipIfOfficeTestOnWindows("images/sample.png");
            var documentPath = TestHelpers.EnsureDocument("images/sample.png", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "image/png" });
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "format", @"{""eq"": ""PNG""}");
        }

        [SkippableFact]
        public void SmokeJsonBasic()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("data_formats/simple.json");
            TestHelpers.SkipIfOfficeTestOnWindows("data_formats/simple.json");
            var documentPath = TestHelpers.EnsureDocument("data_formats/simple.json", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/json" });
            TestHelpers.AssertMinContentLength(result, 5);
        }

        [SkippableFact]
        public void SmokePdfBasic()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdfs/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 50);
            TestHelpers.AssertContentContainsAny(result, new[] { "May 5, 2023", "To Whom it May Concern" });
        }

        [SkippableFact]
        public void SmokeTxtBasic()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("text/report.txt");
            TestHelpers.SkipIfOfficeTestOnWindows("text/report.txt");
            var documentPath = TestHelpers.EnsureDocument("text/report.txt", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "text/plain" });
            TestHelpers.AssertMinContentLength(result, 5);
        }

        [SkippableFact]
        public void SmokeXlsxBasic()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("spreadsheets/stanley_cups.xlsx");
            TestHelpers.SkipIfOfficeTestOnWindows("spreadsheets/stanley_cups.xlsx");
            var documentPath = TestHelpers.EnsureDocument("spreadsheets/stanley_cups.xlsx", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
            TestHelpers.AssertMinContentLength(result, 100);
            TestHelpers.AssertContentContainsAll(result, new[] { "Team", "Location", "Stanley Cups", "Blues", "Flyers", "Maple Leafs", "STL", "PHI", "TOR" });
            TestHelpers.AssertTableCount(result, 1, null);
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "sheet_count", @"{""gte"": 2}");
            TestHelpers.AssertMetadata(metadataNode, "sheet_names", @"{""contains"": [""Stanley Cups""]}");
        }

    }
}
