// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Kreuzberg;
using Xunit;
using Kreuzberg.E2E;

namespace Kreuzberg.E2E.Structured {
    public class StructuredTests
    {
        [SkippableFact]
        public void StructuredJsonBasic()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("json/sample_document.json");
            TestHelpers.SkipIfOfficeTestOnWindows("json/sample_document.json");
            var documentPath = TestHelpers.EnsureDocument("json/sample_document.json", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/json" });
            TestHelpers.AssertMinContentLength(result, 20);
            TestHelpers.AssertContentContainsAny(result, new[] { "Sample Document", "Test Author" });
        }

        [SkippableFact]
        public void StructuredJsonSimple()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("data_formats/simple.json");
            TestHelpers.SkipIfOfficeTestOnWindows("data_formats/simple.json");
            var documentPath = TestHelpers.EnsureDocument("data_formats/simple.json", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/json" });
            TestHelpers.AssertMinContentLength(result, 10);
            TestHelpers.AssertContentContainsAny(result, new[] { "{", "name" });
        }

        [SkippableFact]
        public void StructuredYamlSimple()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("data_formats/simple.yaml");
            TestHelpers.SkipIfOfficeTestOnWindows("data_formats/simple.yaml");
            var documentPath = TestHelpers.EnsureDocument("data_formats/simple.yaml", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/x-yaml" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

    }
}
