name: Setup PaddleOCR Models Cache
description: Download and cache PaddleOCR ONNX models for CI testing

inputs:
  cache-enabled:
    description: Enable model caching (set to false for cross-arch builds)
    required: false
    default: "true"
  models:
    description: Comma-separated list of models to setup (det,cls,rec or specific subset)
    required: false
    default: "det,cls,rec"
  cache-key-suffix:
    description: Suffix for cache key to differentiate model sets
    required: false
    default: "paddle-ocr-v4-onnx"

outputs:
  cache-hit:
    description: Whether models were restored from cache (true/false)
    value: ${{ steps.cache-models.outputs.cache-hit }}
  cache-dir:
    description: Path to the PaddleOCR model cache directory
    value: ${{ steps.set-outputs.outputs.cache-dir }}
  models-available:
    description: Comma-separated list of available models
    value: ${{ steps.verify-models.outputs.available-models }}

runs:
  using: composite
  steps:
    - name: Setup cache directory
      shell: bash
      run: |
        mkdir -p ~/.cache/kreuzberg/paddle-ocr
        echo "Cache directory: $HOME/.cache/kreuzberg/paddle-ocr"

    - name: Restore PaddleOCR models from cache
      if: inputs.cache-enabled == 'true'
      uses: actions/cache@v4
      id: cache-models
      with:
        path: ~/.cache/kreuzberg/paddle-ocr
        key: ${{ inputs.cache-key-suffix }}-${{ runner.os }}-${{ runner.arch }}-v1
        restore-keys: |
          ${{ inputs.cache-key-suffix }}-${{ runner.os }}-${{ runner.arch }}-
          ${{ inputs.cache-key-suffix }}-${{ runner.os }}-
          ${{ inputs.cache-key-suffix }}-

    - name: Download detection model (det)
      if: contains(inputs.models, 'det') && steps.cache-models.outputs.cache-hit != 'true'
      shell: bash
      continue-on-error: true
      run: |
        MODEL_URL="https://huggingface.co/Kreuzberg/paddleocr-onnx-models/resolve/main/en_PP-OCRv4_det_infer.onnx"
        CACHE_DIR="$HOME/.cache/kreuzberg/paddle-ocr"
        MODEL_DIR="$CACHE_DIR/det"
        MODEL_FILE="$MODEL_DIR/model.onnx"

        echo "Downloading detection model from $MODEL_URL"
        mkdir -p "$MODEL_DIR"

        if curl -f -L --progress-bar --connect-timeout 10 --max-time 300 \
          -o "$MODEL_FILE" "$MODEL_URL"; then
          echo "Detection model downloaded successfully ($(du -h "$MODEL_FILE" | cut -f1))"
        else
          echo "Warning: Failed to download detection model, CI will continue without it"
          rm -f "$MODEL_FILE"
        fi

    - name: Download classification model (cls)
      if: contains(inputs.models, 'cls') && steps.cache-models.outputs.cache-hit != 'true'
      shell: bash
      continue-on-error: true
      run: |
        MODEL_URL="https://huggingface.co/Kreuzberg/paddleocr-onnx-models/resolve/main/ch_ppocr_mobile_v2.0_cls_infer.onnx"
        CACHE_DIR="$HOME/.cache/kreuzberg/paddle-ocr"
        MODEL_DIR="$CACHE_DIR/cls"
        MODEL_FILE="$MODEL_DIR/model.onnx"

        echo "Downloading classification model from $MODEL_URL"
        mkdir -p "$MODEL_DIR"

        if curl -f -L --progress-bar --connect-timeout 10 --max-time 300 \
          -o "$MODEL_FILE" "$MODEL_URL"; then
          echo "Classification model downloaded successfully ($(du -h "$MODEL_FILE" | cut -f1))"
        else
          echo "Warning: Failed to download classification model, CI will continue without it"
          rm -f "$MODEL_FILE"
        fi

    - name: Download recognition model (rec)
      if: contains(inputs.models, 'rec') && steps.cache-models.outputs.cache-hit != 'true'
      shell: bash
      continue-on-error: true
      run: |
        MODEL_URL="https://huggingface.co/Kreuzberg/paddleocr-onnx-models/resolve/main/en_PP-OCRv4_rec_infer.onnx"
        CACHE_DIR="$HOME/.cache/kreuzberg/paddle-ocr"
        MODEL_DIR="$CACHE_DIR/rec"
        MODEL_FILE="$MODEL_DIR/model.onnx"

        echo "Downloading recognition model from $MODEL_URL"
        mkdir -p "$MODEL_DIR"

        if curl -f -L --progress-bar --connect-timeout 10 --max-time 300 \
          -o "$MODEL_FILE" "$MODEL_URL"; then
          echo "Recognition model downloaded successfully ($(du -h "$MODEL_FILE" | cut -f1))"
        else
          echo "Warning: Failed to download recognition model, CI will continue without it"
          rm -f "$MODEL_FILE"
        fi

    - name: Verify downloaded models
      id: verify-models
      shell: bash
      run: |
        CACHE_DIR="$HOME/.cache/kreuzberg/paddle-ocr"
        AVAILABLE_MODELS=()
        TOTAL_SIZE=0

        echo "Checking for PaddleOCR models in $CACHE_DIR"

        if [ -f "$CACHE_DIR/det/model.onnx" ]; then
          SIZE=$(du -b "$CACHE_DIR/det/model.onnx" | cut -f1)
          AVAILABLE_MODELS+=("det")
          TOTAL_SIZE=$((TOTAL_SIZE + SIZE))
          echo "  ✓ Detection model: $(numfmt --to=iec-i --suffix=B $SIZE 2>/dev/null || echo $SIZE bytes)"
        fi

        if [ -f "$CACHE_DIR/cls/model.onnx" ]; then
          SIZE=$(du -b "$CACHE_DIR/cls/model.onnx" | cut -f1)
          AVAILABLE_MODELS+=("cls")
          TOTAL_SIZE=$((TOTAL_SIZE + SIZE))
          echo "  ✓ Classification model: $(numfmt --to=iec-i --suffix=B $SIZE 2>/dev/null || echo $SIZE bytes)"
        fi

        if [ -f "$CACHE_DIR/rec/model.onnx" ]; then
          SIZE=$(du -b "$CACHE_DIR/rec/model.onnx" | cut -f1)
          AVAILABLE_MODELS+=("rec")
          TOTAL_SIZE=$((TOTAL_SIZE + SIZE))
          echo "  ✓ Recognition model: $(numfmt --to=iec-i --suffix=B $SIZE 2>/dev/null || echo $SIZE bytes)"
        fi

        if [ ${#AVAILABLE_MODELS[@]} -eq 0 ]; then
          echo "⚠ No models found in cache directory"
          echo "available-models=" >> $GITHUB_OUTPUT
          exit 0
        fi

        AVAILABLE_MODELS_STR=$(IFS=, ; echo "${AVAILABLE_MODELS[*]}")
        echo "✓ Total cached models: ${#AVAILABLE_MODELS[@]} ($(numfmt --to=iec-i --suffix=B $TOTAL_SIZE 2>/dev/null || echo $TOTAL_SIZE bytes))"
        echo "available-models=$AVAILABLE_MODELS_STR" >> $GITHUB_OUTPUT

    - name: Set cache directory output
      id: set-outputs
      shell: bash
      run: |
        CACHE_DIR="$HOME/.cache/kreuzberg/paddle-ocr"
        echo "cache-dir=$CACHE_DIR" >> $GITHUB_OUTPUT
        echo "PADDLE_OCR_MODEL_CACHE=$CACHE_DIR" >> $GITHUB_ENV
        echo "KREUZBERG_CACHE_DIR=$HOME/.cache/kreuzberg" >> $GITHUB_ENV

    - name: Export cache environment
      shell: bash
      run: |
        echo "PADDLE_OCR_MODEL_CACHE=$HOME/.cache/kreuzberg/paddle-ocr" >> $GITHUB_ENV
        echo "KREUZBERG_CACHE_DIR=$HOME/.cache/kreuzberg" >> $GITHUB_ENV
        echo "PaddleOCR model cache configured at: $HOME/.cache/kreuzberg/paddle-ocr"
