name: Cache Binding Artifact
description: Generic cache management for compiled binding artifacts (restore or save)

inputs:
  binding-name:
    description: 'Language binding name (python, ruby, go, java, csharp, php, node, wasm, ffi)'
    required: true
  cache-key:
    description: 'Full cache key for this artifact'
    required: true
  cache-restore-keys:
    description: 'Fallback restore keys (one per line)'
    required: false
    default: ''
  cache-paths:
    description: 'Paths to cache (one per line)'
    required: true
  operation:
    description: 'Operation to perform: restore or save'
    required: true
  enable-crossplatform-cache:
    description: 'Enable cross-OS caching (experimental, may have issues)'
    required: false
    default: 'false'

outputs:
  cache-hit:
    description: 'Whether the cache was restored (exact match)'
    value: ${{ steps.cache-restore.outputs.cache-hit }}
  cache-matched-key:
    description: 'The cache key that was matched (exact or partial)'
    value: ${{ steps.cache-restore.outputs.cache-matched-key || steps.cache-save.outputs.cache-key }}
  cache-primary-key:
    description: 'The primary cache key used'
    value: ${{ inputs.cache-key }}

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ "${{ inputs.operation }}" != "restore" && "${{ inputs.operation }}" != "save" ]]; then
          echo "❌ Error: operation must be 'restore' or 'save'"
          exit 1
        fi

        if [[ -z "${{ inputs.binding-name }}" ]]; then
          echo "❌ Error: binding-name is required"
          exit 1
        fi

        if [[ -z "${{ inputs.cache-key }}" ]]; then
          echo "❌ Error: cache-key is required"
          exit 1
        fi

        if [[ -z "${{ inputs.cache-paths }}" ]]; then
          echo "❌ Error: cache-paths is required"
          exit 1
        fi

        echo "✓ Input validation passed"
        echo "  Binding: ${{ inputs.binding-name }}"
        echo "  Operation: ${{ inputs.operation }}"
        echo "  Cache key: ${{ inputs.cache-key }}"

    - name: Restore cache
      id: cache-restore
      if: inputs.operation == 'restore'
      uses: actions/cache/restore@v5
      with:
        key: ${{ inputs.cache-key }}
        restore-keys: ${{ inputs.cache-restore-keys }}
        path: ${{ inputs.cache-paths }}
        enableCrossOsArchive: ${{ inputs.enable-crossplatform-cache }}
        fail-on-cache-miss: false
        lookup-only: false

    - name: Report cache restore result
      if: inputs.operation == 'restore'
      shell: bash
      run: |
        echo "=== Cache Restore Result for ${{ inputs.binding-name }} ==="

        if [[ "${{ steps.cache-restore.outputs.cache-hit }}" == "true" ]]; then
          echo "✓ Cache HIT (exact match)"
          echo "  Matched key: ${{ steps.cache-restore.outputs.cache-matched-key }}"
        elif [[ -n "${{ steps.cache-restore.outputs.cache-matched-key }}" ]]; then
          echo "⚠ Cache PARTIAL HIT (fallback key matched)"
          echo "  Matched key: ${{ steps.cache-restore.outputs.cache-matched-key }}"
          echo "  Primary key: ${{ inputs.cache-key }}"
        else
          echo "✗ Cache MISS (no match found)"
          echo "  Primary key: ${{ inputs.cache-key }}"
        fi

    - name: Save cache
      id: cache-save
      if: inputs.operation == 'save'
      uses: actions/cache/save@v5
      with:
        key: ${{ inputs.cache-key }}
        path: ${{ inputs.cache-paths }}
        enableCrossOsArchive: ${{ inputs.enable-crossplatform-cache }}

    - name: Report cache save result
      if: inputs.operation == 'save'
      shell: bash
      run: |
        echo "=== Cache Save Result for ${{ inputs.binding-name }} ==="
        echo "✓ Saved to cache"
        echo "  Cache key: ${{ inputs.cache-key }}"
        echo "  Paths cached:"
        echo "${{ inputs.cache-paths }}" | while IFS= read -r path; do
          if [[ -n "$path" ]]; then
            if [[ -e "$path" ]] || ls $path 1> /dev/null 2>&1; then
              echo "    ✓ $path"
            else
              echo "    ⚠ $path (not found, skipped)"
            fi
          fi
        done

    - name: Show cache statistics
      if: always()
      shell: bash
      run: |
        echo ""
        echo "=== Cache Statistics ==="
        echo "Binding: ${{ inputs.binding-name }}"
        echo "Operation: ${{ inputs.operation }}"

        if [[ "${{ inputs.operation }}" == "restore" ]]; then
          echo "Hit: ${{ steps.cache-restore.outputs.cache-hit == 'true' && 'Yes' || 'No' }}"
        fi

        # Calculate total size of cached paths
        TOTAL_SIZE=0
        echo "${{ inputs.cache-paths }}" | while IFS= read -r path; do
          if [[ -n "$path" ]] && [[ -e "$path" ]] || ls $path 1> /dev/null 2>&1; then
            SIZE=$(du -sh "$path" 2>/dev/null | cut -f1 || echo "unknown")
            echo "  $path: $SIZE"
          fi
        done
